### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by TheJaredWilcurt** [edde746/nwjs-sveltekit-boilerplate#1]
```
/nwjs-sveltekit-boilerplate-master>npm install
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '\\nwjs-sveltekit-boilerplate-master\\node_modules\\@sveltejs\\kit',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir '/nwjs-sveltekit-boilerplate-master\node_modules\@sveltejs\kit'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '\\nwjs-sveltekit-boilerplate-master\\node_modules\\@sveltejs\\kit'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '\\nwjs-sveltekit-boilerplate-master\\node_modules\\@sveltejs\\kit',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir '/nwjs-sveltekit-boilerplate-master\node_modules\@sveltejs\kit'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '\\nwjs-sveltekit-boilerplate-master\\node_modules\\@sveltejs\\kit'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /nwjs-sveltekit-boilerplate-master\node_modules\nw
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.mjs
npm ERR! (node:10124) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
npm ERR! (Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! (node:10124) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
npm ERR! /nwjs-sveltekit-boilerplate-master\node_modules\@eggjs\yauzl\index.js:187
npm ERR!     callback(new Error("end of central directory record signature not found"));
npm ERR!              ^
npm ERR!
npm ERR! Error [ZipUncompressStreamError]: end of central directory record signature not found
npm ERR!     at /nwjs-sveltekit-boilerplate-master\node_modules\@eggjs\yauzl\index.js:187:14
npm ERR!     at /nwjs-sveltekit-boilerplate-master\node_modules\@eggjs\yauzl\index.js:631:5
npm ERR!     at /nwjs-sveltekit-boilerplate-master\node_modules\fd-slicer2\index.js:21:9
npm ERR!     at FSReqCallback.wrapper [as oncomplete] (node:fs:701:5)
npm ERR!
npm ERR! Node.js v20.5.0
```

**Comment by edde746** [comment]
Fixed with https://github.com/edde746/nwjs-sveltekit-boilerplate/commit/cbe2292872c610a2ed93ec0b14983b474cb3b4e6
